name: Build and Push Docker Image

# This workflow runs whenever code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx to build Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub using the secrets you set earlier
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and tag the Docker image
      - name: Build and tag Docker image
        run: |
          docker build -t tracyo/banapp:latest .
          docker tag tracyo/banapp:latest tracyo/banapp:v1.0

      # Step 5: Push the newly built image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push tracyo/banapp:latest
          docker push tracyo/banapp:v1.0
